import BorceaVariance
import Solution

-- Full polynomial target and its proof.
#check Challenge
#check solution
#check BorceaVariance.MainStatement

-- Numerical leaves are audited transitively through every block exclusion.

-- BorceaVariance/BasicProduct.lean:12
#check BorceaVariance.phi_nonneg
-- BorceaVariance/BasicProduct.lean:16
#check BorceaVariance.phi_sq
-- BorceaVariance/BasicProduct.lean:30
#check BorceaVariance.phi_le_one
-- BorceaVariance/BasicProduct.lean:49
#check BorceaVariance.phi_le_psi
-- BorceaVariance/BasicProduct.lean:61
#check BorceaVariance.normalized_other_shift_energy
-- BorceaVariance/BasicProduct.lean:76
#check BorceaVariance.normalized_basic_product
-- BorceaVariance/Certificate/Arithmetic.lean:18
#check BorceaVariance.Certificate.multiplyUp_sound
-- BorceaVariance/Certificate/Arithmetic.lean:26
#check BorceaVariance.Certificate.subtractDown_sound
-- BorceaVariance/Certificate/Arithmetic.lean:33
#check BorceaVariance.Certificate.upperPower_sound
-- BorceaVariance/Certificate/Arithmetic.lean:37
#check BorceaVariance.Certificate.upperSqrt_sound
-- BorceaVariance/Certificate/Arithmetic.lean:41
#check BorceaVariance.Certificate.upperHalfPower_sound
-- BorceaVariance/Certificate/Arithmetic.lean:49
#check BorceaVariance.Certificate.taylor32_le_exp
-- BorceaVariance/Certificate/BetaMajorant.lean:13
#check BorceaVariance.Certificate.varianceBox_upper
-- BorceaVariance/Certificate/BetaMajorant.lean:25
#check BorceaVariance.Certificate.rhoLower_sound
-- BorceaVariance/Certificate/BetaMajorant.lean:70
#check BorceaVariance.Certificate.betaCoefficient_lower
-- BorceaVariance/Certificate/BetaMajorant.lean:83
#check BorceaVariance.Certificate.beta_majorant_sound
-- BorceaVariance/Certificate/CenterDenominator.lean:8
#check BorceaVariance.Certificate.center_denominator_lower
-- BorceaVariance/Certificate/CenterFirstPointwise.lean:12
#check BorceaVariance.Certificate.center_first_coefficients_bounds
-- BorceaVariance/Certificate/CenterFirstPointwise.lean:30
#check BorceaVariance.Certificate.center_first_box_pointwise
-- BorceaVariance/Certificate/CenterQuadrature.lean:35
#check BorceaVariance.Certificate.centered_error_norm_continuous
-- BorceaVariance/Certificate/CenterQuadrature.lean:40
#check BorceaVariance.Certificate.center_second_segment_bound
-- BorceaVariance/Certificate/CenterQuadrature.lean:75
#check BorceaVariance.Certificate.center_first_segment_bound
-- BorceaVariance/Certificate/CenterQuadrature.lean:110
#check BorceaVariance.Certificate.center_segment_bound
-- BorceaVariance/Certificate/CenterQuadrature.lean:129
#check BorceaVariance.Certificate.center_quadrature_bound
-- BorceaVariance/Certificate/CenterQuadrature.lean:144
#check BorceaVariance.Certificate.center_error_integral_rounded
-- BorceaVariance/Certificate/CenterScalarBounds.lean:7
#check BorceaVariance.Certificate.half_power_unit_box
-- BorceaVariance/Certificate/CenterScalarBounds.lean:18
#check BorceaVariance.Certificate.centerEndpointSquare_le_one
-- BorceaVariance/Certificate/CenterScalarBounds.lean:27
#check BorceaVariance.Certificate.center_endpoint_power_upper
-- BorceaVariance/Certificate/CenterScalarBounds.lean:41
#check BorceaVariance.Certificate.center_integral_factor_bounds
-- BorceaVariance/Certificate/CenterScalarBounds.lean:63
#check BorceaVariance.Certificate.center_integral_term_upper
-- BorceaVariance/Certificate/CenterSecondPointwise.lean:13
#check BorceaVariance.Certificate.center_second_coefficients_bounds
-- BorceaVariance/Certificate/CenterSecondPointwise.lean:28
#check BorceaVariance.Certificate.center_second_box_pointwise
-- BorceaVariance/Certificate/Checker.lean:23
#check BorceaVariance.Certificate.box_exclusion_of_eq
-- BorceaVariance/Certificate/Checker.lean:66
#check BorceaVariance.Certificate.leaf_check_sound
-- BorceaVariance/Certificate/Checker.lean:123
#check BorceaVariance.Certificate.Tree.checked_exclusion
-- BorceaVariance/Certificate/CoefficientArithmetic.lean:19
#check BorceaVariance.Certificate.powerSumRat_cast
-- BorceaVariance/Certificate/CoefficientArithmetic.lean:25
#check BorceaVariance.Certificate.coefficient_base_bounds
-- BorceaVariance/Certificate/CoefficientArithmetic.lean:49
#check BorceaVariance.Certificate.coefficient_sum_rounded_upper
-- BorceaVariance/Certificate/CompactDomain.lean:6
#check BorceaVariance.Certificate.CounterexampleParameters.in_initialBox
-- BorceaVariance/Certificate/CompactDomain.lean:17
#check BorceaVariance.Certificate.admissible_in_initialBox
-- BorceaVariance/Certificate/CompactDomain.lean:22
#check BorceaVariance.Certificate.no_counterexample_of_initialBox_excluded
-- BorceaVariance/Certificate/CoreBounds.lean:16
#check BorceaVariance.Certificate.phi_box_upper
-- BorceaVariance/Certificate/CoreBounds.lean:38
#check BorceaVariance.Certificate.reciprocal_product_box_upper
-- BorceaVariance/Certificate/CoreBounds.lean:58
#check BorceaVariance.Certificate.core_box_upper
-- BorceaVariance/Certificate/DegreeCoverage.lean:10
#check BorceaVariance.Certificate.degreeChain_coverage
-- BorceaVariance/Certificate/DirectPointwise.lean:12
#check BorceaVariance.Certificate.direct_coefficients_bounds
-- BorceaVariance/Certificate/DirectPointwise.lean:27
#check BorceaVariance.Certificate.direct_coefficients_nonneg
-- BorceaVariance/Certificate/DirectPointwise.lean:37
#check BorceaVariance.Certificate.direct_box_pointwise
-- BorceaVariance/Certificate/DirectQuadrature.lean:24
#check BorceaVariance.Certificate.direct_segment_bound
-- BorceaVariance/Certificate/DirectQuadrature.lean:74
#check BorceaVariance.Certificate.direct_quadrature_bound
-- BorceaVariance/Certificate/Distances.lean:5
#check BorceaVariance.Certificate.norm_mean_sub_real_lower
-- BorceaVariance/Certificate/Distances.lean:13
#check BorceaVariance.Certificate.norm_one_sub_product_lower
-- BorceaVariance/Certificate/Distances.lean:25
#check BorceaVariance.Certificate.distanceA_lower
-- BorceaVariance/Certificate/Distances.lean:39
#check BorceaVariance.Certificate.distanceB_lower
-- BorceaVariance/Certificate/EndpointBounds.lean:9
#check BorceaVariance.Certificate.endpoint_square_upper
-- BorceaVariance/Certificate/EndpointBounds.lean:34
#check BorceaVariance.Certificate.endpoint_kappa_bound
-- BorceaVariance/Certificate/EndpointBounds.lean:42
#check BorceaVariance.Certificate.linear_majorant_box
-- BorceaVariance/Certificate/EndpointBounds.lean:50
#check BorceaVariance.Certificate.rhoLower_nonneg
-- BorceaVariance/Certificate/EndpointBounds.lean:57
#check BorceaVariance.Certificate.beta_box_unit_bounds
-- BorceaVariance/Certificate/EnvelopeQuadrature.lean:7
#check BorceaVariance.Certificate.quadratic_chord_two_bound
-- BorceaVariance/Certificate/EnvelopeQuadrature.lean:30
#check BorceaVariance.Certificate.linear_chord_two_bound
-- BorceaVariance/Certificate/Generated/Accepted0.lean:1613
#check BorceaVariance.Certificate.Generated.certificateBlock0_exclusion
-- BorceaVariance/Certificate/Generated/Accepted1.lean:3335
#check BorceaVariance.Certificate.Generated.certificateBlock1_exclusion
-- BorceaVariance/Certificate/Generated/Accepted10.lean:8121
#check BorceaVariance.Certificate.Generated.certificateBlock10_exclusion
-- BorceaVariance/Certificate/Generated/Accepted11.lean:7825
#check BorceaVariance.Certificate.Generated.certificateBlock11_exclusion
-- BorceaVariance/Certificate/Generated/Accepted12.lean:4692
#check BorceaVariance.Certificate.Generated.certificateBlock12_exclusion
-- BorceaVariance/Certificate/Generated/Accepted13.lean:3458
#check BorceaVariance.Certificate.Generated.certificateBlock13_exclusion
-- BorceaVariance/Certificate/Generated/Accepted14.lean:2662
#check BorceaVariance.Certificate.Generated.certificateBlock14_exclusion
-- BorceaVariance/Certificate/Generated/Accepted15.lean:2225
#check BorceaVariance.Certificate.Generated.certificateBlock15_exclusion
-- BorceaVariance/Certificate/Generated/Accepted16.lean:2092
#check BorceaVariance.Certificate.Generated.certificateBlock16_exclusion
-- BorceaVariance/Certificate/Generated/Accepted17.lean:1854
#check BorceaVariance.Certificate.Generated.certificateBlock17_exclusion
-- BorceaVariance/Certificate/Generated/Accepted18.lean:1724
#check BorceaVariance.Certificate.Generated.certificateBlock18_exclusion
-- BorceaVariance/Certificate/Generated/Accepted19.lean:1562
#check BorceaVariance.Certificate.Generated.certificateBlock19_exclusion
-- BorceaVariance/Certificate/Generated/Accepted2.lean:4815
#check BorceaVariance.Certificate.Generated.certificateBlock2_exclusion
-- BorceaVariance/Certificate/Generated/Accepted20.lean:1405
#check BorceaVariance.Certificate.Generated.certificateBlock20_exclusion
-- BorceaVariance/Certificate/Generated/Accepted21.lean:1411
#check BorceaVariance.Certificate.Generated.certificateBlock21_exclusion
-- BorceaVariance/Certificate/Generated/Accepted22.lean:1335
#check BorceaVariance.Certificate.Generated.certificateBlock22_exclusion
-- BorceaVariance/Certificate/Generated/Accepted23.lean:1239
#check BorceaVariance.Certificate.Generated.certificateBlock23_exclusion
-- BorceaVariance/Certificate/Generated/Accepted24.lean:1148
#check BorceaVariance.Certificate.Generated.certificateBlock24_exclusion
-- BorceaVariance/Certificate/Generated/Accepted25.lean:1097
#check BorceaVariance.Certificate.Generated.certificateBlock25_exclusion
-- BorceaVariance/Certificate/Generated/Accepted26.lean:1031
#check BorceaVariance.Certificate.Generated.certificateBlock26_exclusion
-- BorceaVariance/Certificate/Generated/Accepted27.lean:1224
#check BorceaVariance.Certificate.Generated.certificateBlock27_exclusion
-- BorceaVariance/Certificate/Generated/Accepted28.lean:1025
#check BorceaVariance.Certificate.Generated.certificateBlock28_exclusion
-- BorceaVariance/Certificate/Generated/Accepted29.lean:1016
#check BorceaVariance.Certificate.Generated.certificateBlock29_exclusion
-- BorceaVariance/Certificate/Generated/Accepted3.lean:7668
#check BorceaVariance.Certificate.Generated.certificateBlock3_exclusion
-- BorceaVariance/Certificate/Generated/Accepted30.lean:889
#check BorceaVariance.Certificate.Generated.certificateBlock30_exclusion
-- BorceaVariance/Certificate/Generated/Accepted31.lean:780
#check BorceaVariance.Certificate.Generated.certificateBlock31_exclusion
-- BorceaVariance/Certificate/Generated/Accepted32.lean:747
#check BorceaVariance.Certificate.Generated.certificateBlock32_exclusion
-- BorceaVariance/Certificate/Generated/Accepted33.lean:660
#check BorceaVariance.Certificate.Generated.certificateBlock33_exclusion
-- BorceaVariance/Certificate/Generated/Accepted34.lean:618
#check BorceaVariance.Certificate.Generated.certificateBlock34_exclusion
-- BorceaVariance/Certificate/Generated/Accepted35.lean:572
#check BorceaVariance.Certificate.Generated.certificateBlock35_exclusion
-- BorceaVariance/Certificate/Generated/Accepted36.lean:518
#check BorceaVariance.Certificate.Generated.certificateBlock36_exclusion
-- BorceaVariance/Certificate/Generated/Accepted37.lean:485
#check BorceaVariance.Certificate.Generated.certificateBlock37_exclusion
-- BorceaVariance/Certificate/Generated/Accepted38.lean:500
#check BorceaVariance.Certificate.Generated.certificateBlock38_exclusion
-- BorceaVariance/Certificate/Generated/Accepted39.lean:467
#check BorceaVariance.Certificate.Generated.certificateBlock39_exclusion
-- BorceaVariance/Certificate/Generated/Accepted4.lean:5295
#check BorceaVariance.Certificate.Generated.certificateBlock4_exclusion
-- BorceaVariance/Certificate/Generated/Accepted40.lean:449
#check BorceaVariance.Certificate.Generated.certificateBlock40_exclusion
-- BorceaVariance/Certificate/Generated/Accepted41.lean:485
#check BorceaVariance.Certificate.Generated.certificateBlock41_exclusion
-- BorceaVariance/Certificate/Generated/Accepted42.lean:458
#check BorceaVariance.Certificate.Generated.certificateBlock42_exclusion
-- BorceaVariance/Certificate/Generated/Accepted43.lean:367
#check BorceaVariance.Certificate.Generated.certificateBlock43_exclusion
-- BorceaVariance/Certificate/Generated/Accepted44.lean:337
#check BorceaVariance.Certificate.Generated.certificateBlock44_exclusion
-- BorceaVariance/Certificate/Generated/Accepted45.lean:331
#check BorceaVariance.Certificate.Generated.certificateBlock45_exclusion
-- BorceaVariance/Certificate/Generated/Accepted46.lean:286
#check BorceaVariance.Certificate.Generated.certificateBlock46_exclusion
-- BorceaVariance/Certificate/Generated/Accepted47.lean:286
#check BorceaVariance.Certificate.Generated.certificateBlock47_exclusion
-- BorceaVariance/Certificate/Generated/Accepted48.lean:259
#check BorceaVariance.Certificate.Generated.certificateBlock48_exclusion
-- BorceaVariance/Certificate/Generated/Accepted49.lean:247
#check BorceaVariance.Certificate.Generated.certificateBlock49_exclusion
-- BorceaVariance/Certificate/Generated/Accepted5.lean:4291
#check BorceaVariance.Certificate.Generated.certificateBlock5_exclusion
-- BorceaVariance/Certificate/Generated/Accepted50.lean:265
#check BorceaVariance.Certificate.Generated.certificateBlock50_exclusion
-- BorceaVariance/Certificate/Generated/Accepted51.lean:256
#check BorceaVariance.Certificate.Generated.certificateBlock51_exclusion
-- BorceaVariance/Certificate/Generated/Accepted52.lean:262
#check BorceaVariance.Certificate.Generated.certificateBlock52_exclusion
-- BorceaVariance/Certificate/Generated/Accepted53.lean:229
#check BorceaVariance.Certificate.Generated.certificateBlock53_exclusion
-- BorceaVariance/Certificate/Generated/Accepted54.lean:259
#check BorceaVariance.Certificate.Generated.certificateBlock54_exclusion
-- BorceaVariance/Certificate/Generated/Accepted55.lean:253
#check BorceaVariance.Certificate.Generated.certificateBlock55_exclusion
-- BorceaVariance/Certificate/Generated/Accepted56.lean:241
#check BorceaVariance.Certificate.Generated.certificateBlock56_exclusion
-- BorceaVariance/Certificate/Generated/Accepted57.lean:259
#check BorceaVariance.Certificate.Generated.certificateBlock57_exclusion
-- BorceaVariance/Certificate/Generated/Accepted58.lean:256
#check BorceaVariance.Certificate.Generated.certificateBlock58_exclusion
-- BorceaVariance/Certificate/Generated/Accepted59.lean:235
#check BorceaVariance.Certificate.Generated.certificateBlock59_exclusion
-- BorceaVariance/Certificate/Generated/Accepted6.lean:3519
#check BorceaVariance.Certificate.Generated.certificateBlock6_exclusion
-- BorceaVariance/Certificate/Generated/Accepted60.lean:226
#check BorceaVariance.Certificate.Generated.certificateBlock60_exclusion
-- BorceaVariance/Certificate/Generated/Accepted61.lean:259
#check BorceaVariance.Certificate.Generated.certificateBlock61_exclusion
-- BorceaVariance/Certificate/Generated/Accepted62.lean:247
#check BorceaVariance.Certificate.Generated.certificateBlock62_exclusion
-- BorceaVariance/Certificate/Generated/Accepted63.lean:247
#check BorceaVariance.Certificate.Generated.certificateBlock63_exclusion
-- BorceaVariance/Certificate/Generated/Accepted64.lean:259
#check BorceaVariance.Certificate.Generated.certificateBlock64_exclusion
-- BorceaVariance/Certificate/Generated/Accepted65.lean:253
#check BorceaVariance.Certificate.Generated.certificateBlock65_exclusion
-- BorceaVariance/Certificate/Generated/Accepted66.lean:241
#check BorceaVariance.Certificate.Generated.certificateBlock66_exclusion
-- BorceaVariance/Certificate/Generated/Accepted67.lean:241
#check BorceaVariance.Certificate.Generated.certificateBlock67_exclusion
-- BorceaVariance/Certificate/Generated/Accepted68.lean:259
#check BorceaVariance.Certificate.Generated.certificateBlock68_exclusion
-- BorceaVariance/Certificate/Generated/Accepted69.lean:259
#check BorceaVariance.Certificate.Generated.certificateBlock69_exclusion
-- BorceaVariance/Certificate/Generated/Accepted7.lean:3030
#check BorceaVariance.Certificate.Generated.certificateBlock7_exclusion
-- BorceaVariance/Certificate/Generated/Accepted70.lean:259
#check BorceaVariance.Certificate.Generated.certificateBlock70_exclusion
-- BorceaVariance/Certificate/Generated/Accepted71.lean:256
#check BorceaVariance.Certificate.Generated.certificateBlock71_exclusion
-- BorceaVariance/Certificate/Generated/Accepted8.lean:2735
#check BorceaVariance.Certificate.Generated.certificateBlock8_exclusion
-- BorceaVariance/Certificate/Generated/Accepted9.lean:2448
#check BorceaVariance.Certificate.Generated.certificateBlock9_exclusion
-- BorceaVariance/Certificate/Generated/Certificates.lean:91
#check BorceaVariance.Certificate.Generated.certificates_degree_list
-- BorceaVariance/Certificate/Generated/Certificates.lean:93
#check BorceaVariance.Certificate.Generated.concrete_degree_coverage
-- BorceaVariance/Certificate/Generated/Certificates.lean:100
#check BorceaVariance.Certificate.Generated.concrete_tree_coverage
-- BorceaVariance/Certificate/Generated/Certificates.lean:106
#check BorceaVariance.Certificate.Generated.concrete_paths_no_duplicates
-- BorceaVariance/Certificate/Generated/Certificates.lean:109
#check BorceaVariance.Certificate.Generated.concrete_leaf_has_no_descendant
-- BorceaVariance/Certificate/Generated/Counts.lean:9
#check BorceaVariance.Certificate.Generated.concrete_certificate_count
-- BorceaVariance/Certificate/Generated/Counts.lean:11
#check BorceaVariance.Certificate.Generated.concrete_low_leaf_count
-- BorceaVariance/Certificate/Generated/Counts.lean:15
#check BorceaVariance.Certificate.Generated.concrete_mid_leaf_count
-- BorceaVariance/Certificate/Generated/Counts.lean:19
#check BorceaVariance.Certificate.Generated.concrete_total_leaf_count
-- BorceaVariance/Certificate/Generated/DegreeBlocks.lean:80
#check BorceaVariance.Certificate.Generated.degreeBlocks_count
-- BorceaVariance/Certificate/Generated/DegreeBlocks.lean:82
#check BorceaVariance.Certificate.Generated.degreeBlocks_chain
-- BorceaVariance/Certificate/Generated/DegreeBlocks.lean:84
#check BorceaVariance.Certificate.Generated.degreeBlocks_no_overlap
-- BorceaVariance/Certificate/Generated/DegreeBlocks.lean:88
#check BorceaVariance.Certificate.Generated.degreeBlocks_coverage
-- BorceaVariance/Certificate/IntegralEnvelopes.lean:14
#check BorceaVariance.Certificate.quadraticValue_cast
-- BorceaVariance/Certificate/IntegralEnvelopes.lean:18
#check BorceaVariance.Certificate.linearValue_cast
-- BorceaVariance/Certificate/IntegralEnvelopes.lean:22
#check BorceaVariance.Certificate.quadratic_envelope_bounds
-- BorceaVariance/Certificate/IntegralEnvelopes.lean:41
#check BorceaVariance.Certificate.refined_kappa_bound
-- BorceaVariance/Certificate/IntegralEnvelopes.lean:52
#check BorceaVariance.Certificate.linear_envelope_bounds
-- BorceaVariance/Certificate/IntegralEnvelopes.lean:64
#check BorceaVariance.Certificate.quadratic_envelope_power_convex
-- BorceaVariance/Certificate/IntegralEnvelopes.lean:70
#check BorceaVariance.Certificate.linear_envelope_power_convex
-- BorceaVariance/Certificate/IntegralEnvelopes.lean:75
#check BorceaVariance.Certificate.quadratic_envelope_power_continuous
-- BorceaVariance/Certificate/IntegralEnvelopes.lean:81
#check BorceaVariance.Certificate.linear_envelope_power_continuous
-- BorceaVariance/Certificate/IntegralEnvelopes.lean:87
#check BorceaVariance.Certificate.quadratic_envelope_power_rounded
-- BorceaVariance/Certificate/IntegralEnvelopes.lean:94
#check BorceaVariance.Certificate.linear_envelope_power_rounded
-- BorceaVariance/Certificate/IntervalMoments.lean:11
#check BorceaVariance.Certificate.moment_A_exclusion
-- BorceaVariance/Certificate/IntervalMoments.lean:45
#check BorceaVariance.Certificate.moment_B_exclusion
-- BorceaVariance/Certificate/Mesh.lean:13
#check BorceaVariance.Certificate.meshCheck_sound
-- BorceaVariance/Certificate/Mesh.lean:23
#check BorceaVariance.Certificate.sum_segment_upper_bounds
-- BorceaVariance/Certificate/Mesh.lean:42
#check BorceaVariance.Certificate.segment_majorant_one
-- BorceaVariance/Certificate/Mesh.lean:59
#check BorceaVariance.Certificate.segment_majorant_two
-- BorceaVariance/Certificate/Moments.lean:7
#check BorceaVariance.Certificate.CounterexampleParameters.critical_centered
-- BorceaVariance/Certificate/Moments.lean:11
#check BorceaVariance.Certificate.CounterexampleParameters.critical_secondMoment_bound
-- BorceaVariance/Certificate/Moments.lean:15
#check BorceaVariance.Certificate.CounterexampleParameters.moments
-- BorceaVariance/Certificate/Moments.lean:28
#check BorceaVariance.Certificate.CounterexampleParameters.distinguished_pos
-- BorceaVariance/Certificate/Moments.lean:32
#check BorceaVariance.Certificate.CounterexampleParameters.mean_re_pos
-- BorceaVariance/Certificate/PackedBounds.lean:14
#check BorceaVariance.Certificate.packed_variance_box_bound
-- BorceaVariance/Certificate/PackedBounds.lean:29
#check BorceaVariance.Certificate.packed_distance_box_bound
-- BorceaVariance/Certificate/PackingWitness.lean:34
#check BorceaVariance.Certificate.defect_div_sqrt_upper
-- BorceaVariance/Certificate/PackingWitness.lean:44
#check BorceaVariance.Certificate.packing_box_bounds
-- BorceaVariance/Certificate/PackingWitness.lean:106
#check BorceaVariance.Certificate.packing_distance_square_upper
-- BorceaVariance/Certificate/Parameters.lean:25
#check BorceaVariance.Certificate.CounterexampleParameters.critical_far
-- BorceaVariance/Certificate/Parameters.lean:32
#check BorceaVariance.Certificate.parameters_exist
-- BorceaVariance/Certificate/Parameters.lean:37
#check BorceaVariance.Certificate.CounterexampleParameters.variance_nonnegative
-- BorceaVariance/Certificate/Parameters.lean:44
#check BorceaVariance.Certificate.CounterexampleParameters.unit_parameters
-- BorceaVariance/Certificate/Paths.lean:18
#check BorceaVariance.Certificate.Tree.leafPaths_nodup
-- BorceaVariance/Certificate/Paths.lean:31
#check BorceaVariance.Certificate.Tree.atLeaf_unique
-- BorceaVariance/Certificate/Paths.lean:47
#check BorceaVariance.Certificate.Tree.leaf_has_no_descendant
-- BorceaVariance/Certificate/Paths.lean:67
#check BorceaVariance.Certificate.Tree.atLeaf_split_coordinate
-- BorceaVariance/Certificate/PositiveGeometry.lean:14
#check BorceaVariance.Certificate.positive_pointwise_lower
-- BorceaVariance/Certificate/PositiveGeometry.lean:42
#check BorceaVariance.Certificate.real_coordinate_lower_mono
-- BorceaVariance/Certificate/PositiveGeometry.lean:67
#check BorceaVariance.Certificate.positive_real_variance_upper
-- BorceaVariance/Certificate/PositiveGeometry.lean:121
#check BorceaVariance.Certificate.positive_quadratic_lower
-- BorceaVariance/Certificate/PositiveKernel.lean:11
#check BorceaVariance.Certificate.integralRat_cast
-- BorceaVariance/Certificate/PositiveKernel.lean:16
#check BorceaVariance.Certificate.integral_polynomial_mono
-- BorceaVariance/Certificate/PositiveKernel.lean:24
#check BorceaVariance.Certificate.positive_h_bounds
-- BorceaVariance/Certificate/PositiveKernel.lean:43
#check BorceaVariance.Certificate.positive_kernel_lower
-- BorceaVariance/Certificate/PositiveKernel.lean:71
#check BorceaVariance.Certificate.phase_error_mono_h
-- BorceaVariance/Certificate/PositiveKernel.lean:96
#check BorceaVariance.Certificate.positive_phase_error_upper
-- BorceaVariance/Certificate/PositivePhase.lean:12
#check BorceaVariance.Certificate.positive_mean_real_lower
-- BorceaVariance/Certificate/PositivePhase.lean:42
#check BorceaVariance.Certificate.positive_phase_square_upper
-- BorceaVariance/Certificate/PositivePhase.lean:68
#check BorceaVariance.Certificate.positive_phase_rounded_upper
-- BorceaVariance/Certificate/PrimitiveBasic.lean:12
#check BorceaVariance.Certificate.degree_bound_sound
-- BorceaVariance/Certificate/PrimitiveBasic.lean:28
#check BorceaVariance.Certificate.variance_nonnegative_sound
-- BorceaVariance/Certificate/PrimitiveBeta.lean:12
#check BorceaVariance.Certificate.beta_negative_sound
-- BorceaVariance/Certificate/PrimitiveCenterAbsolute.lean:22
#check BorceaVariance.Certificate.center_absolute_sound
-- BorceaVariance/Certificate/PrimitiveCenterRatio.lean:15
#check BorceaVariance.Certificate.center_ratio_sound
-- BorceaVariance/Certificate/PrimitiveCoefficient.lean:18
#check BorceaVariance.Certificate.coefficient_sound
-- BorceaVariance/Certificate/PrimitiveDirect.lean:12
#check BorceaVariance.Certificate.refined_endpoint_power_upper
-- BorceaVariance/Certificate/PrimitiveDirect.lean:31
#check BorceaVariance.Certificate.direct_scalar_exclusion
-- BorceaVariance/Certificate/PrimitiveDirect.lean:91
#check BorceaVariance.Certificate.direct_sound
-- BorceaVariance/Certificate/PrimitiveMoments.lean:8
#check BorceaVariance.Certificate.varianceUpper_bounds
-- BorceaVariance/Certificate/PrimitiveMoments.lean:25
#check BorceaVariance.Certificate.inverse_moment_sound
-- BorceaVariance/Certificate/PrimitiveMoments.lean:56
#check BorceaVariance.Certificate.moment_A_sound
-- BorceaVariance/Certificate/PrimitiveMoments.lean:86
#check BorceaVariance.Certificate.moment_B_sound
-- BorceaVariance/Certificate/PrimitiveNear.lean:9
#check BorceaVariance.Certificate.near_uniform_sound
-- BorceaVariance/Certificate/PrimitivePacked.lean:21
#check BorceaVariance.Certificate.product_logcap_sound
-- BorceaVariance/Certificate/PrimitivePacked.lean:39
#check BorceaVariance.Certificate.critical_variance_packed_sound
-- BorceaVariance/Certificate/PrimitivePacked.lean:51
#check BorceaVariance.Certificate.moment_A_packed_sound
-- BorceaVariance/Certificate/PrimitivePacked.lean:63
#check BorceaVariance.Certificate.moment_B_packed_sound
-- BorceaVariance/Certificate/PrimitivePositive.lean:22
#check BorceaVariance.Certificate.positive_sound
-- BorceaVariance/Certificate/PrimitiveProduct.lean:10
#check BorceaVariance.Certificate.productBase_bounds
-- BorceaVariance/Certificate/PrimitiveProduct.lean:45
#check BorceaVariance.Certificate.product_sound
-- BorceaVariance/Certificate/PrimitiveRadial.lean:17
#check BorceaVariance.Certificate.radial_denominator_lower
-- BorceaVariance/Certificate/PrimitiveRadial.lean:38
#check BorceaVariance.Certificate.radial_mean_box_bound
-- BorceaVariance/Certificate/PrimitiveRadial.lean:59
#check BorceaVariance.Certificate.radial_variance_box_bound
-- BorceaVariance/Certificate/PrimitiveRadial.lean:85
#check BorceaVariance.Certificate.initial_variance_box_bound
-- BorceaVariance/Certificate/PrimitiveRadial.lean:100
#check BorceaVariance.Certificate.finite_radial_sound
-- BorceaVariance/Certificate/PrimitiveRadial.lean:122
#check BorceaVariance.Certificate.initial_critical_variance_negative_sound
-- BorceaVariance/Certificate/PrimitiveRefinedBeta.lean:9
#check BorceaVariance.Certificate.quadratic_negative_exclusion
-- BorceaVariance/Certificate/PrimitiveRefinedBeta.lean:34
#check BorceaVariance.Certificate.refined_beta_negative_sound
-- BorceaVariance/Certificate/PrimitiveRetained.lean:12
#check BorceaVariance.Certificate.retained_direct_sound
-- BorceaVariance/Certificate/PrimitiveRootRadial.lean:7
#check BorceaVariance.Certificate.reciprocal_product_le_one
-- BorceaVariance/Certificate/PrimitiveRootRadial.lean:24
#check BorceaVariance.Certificate.product_radial_sound
-- BorceaVariance/Certificate/PrimitiveRootStable.lean:7
#check BorceaVariance.Certificate.rootProductLower_pos
-- BorceaVariance/Certificate/PrimitiveRootStable.lean:15
#check BorceaVariance.Certificate.root_product_exp_bound
-- BorceaVariance/Certificate/PrimitiveRootStable.lean:43
#check BorceaVariance.Certificate.product_root_stable_sound
-- BorceaVariance/Certificate/PrimitiveStableProduct.lean:13
#check BorceaVariance.Certificate.radialDistance_nonneg
-- BorceaVariance/Certificate/PrimitiveStableProduct.lean:15
#check BorceaVariance.Certificate.radialDistance_lower
-- BorceaVariance/Certificate/PrimitiveStableProduct.lean:39
#check BorceaVariance.Certificate.stableBoxLoss_nonneg
-- BorceaVariance/Certificate/PrimitiveStableProduct.lean:48
#check BorceaVariance.Certificate.stableBoxLoss_lower
-- BorceaVariance/Certificate/PrimitiveStableProduct.lean:86
#check BorceaVariance.Certificate.product_stable_sound
-- BorceaVariance/Certificate/RealScaledMesh.lean:7
#check BorceaVariance.Certificate.segment_majorant_two_real_scale
-- BorceaVariance/Certificate/RealScaledMesh.lean:29
#check BorceaVariance.Certificate.sum_segment_scaled_upper_bounds
-- BorceaVariance/Certificate/RealScaledMesh.lean:50
#check BorceaVariance.Certificate.segment_majorant_two_factored
-- BorceaVariance/Certificate/RefinedBeta.lean:13
#check BorceaVariance.Certificate.rho_variance_lower
-- BorceaVariance/Certificate/RefinedBeta.lean:60
#check BorceaVariance.Certificate.rho_distance_lower
-- BorceaVariance/Certificate/RefinedBeta.lean:84
#check BorceaVariance.Certificate.beta_majorant_of_rho
-- BorceaVariance/Certificate/RefinedEndpoint.lean:15
#check BorceaVariance.Certificate.varianceBoxLower_bound
-- BorceaVariance/Certificate/RefinedEndpoint.lean:29
#check BorceaVariance.Certificate.refined_endpoint_square_upper
-- BorceaVariance/Certificate/RefinedEndpoint.lean:57
#check BorceaVariance.Certificate.center_endpoint_square_upper
-- BorceaVariance/Certificate/RefinedEndpoint.lean:95
#check BorceaVariance.Certificate.endpoint_bound_of_square
-- BorceaVariance/Certificate/RefinedMoments.lean:5
#check BorceaVariance.Certificate.CounterexampleParameters.initial_moments
-- BorceaVariance/Certificate/RefinedMoments.lean:24
#check BorceaVariance.Certificate.initial_inverse_moment_sound
-- BorceaVariance/Certificate/RefinedMoments.lean:60
#check BorceaVariance.Certificate.initial_moment_A_sound
-- BorceaVariance/Certificate/RefinedMoments.lean:94
#check BorceaVariance.Certificate.initial_moment_B_sound
-- BorceaVariance/Certificate/RefinedRho.lean:6
#check BorceaVariance.Certificate.refinedVariance_le_one
-- BorceaVariance/Certificate/RefinedRho.lean:33
#check BorceaVariance.Certificate.refined_rho_lower
-- BorceaVariance/Certificate/RefinedRho.lean:51
#check BorceaVariance.Certificate.refined_rho_nonneg
-- BorceaVariance/Certificate/RefinedRho.lean:64
#check BorceaVariance.Certificate.refined_beta_majorant
-- BorceaVariance/Certificate/RefinementEvidence.lean:24
#check BorceaVariance.Certificate.refinement_check_domain
-- BorceaVariance/Certificate/RefinementEvidence.lean:30
#check BorceaVariance.Certificate.refinement_check_degree_order
-- BorceaVariance/Certificate/RefinementEvidence.lean:34
#check BorceaVariance.Certificate.refined_variance_bound
-- BorceaVariance/Certificate/RefinementEvidence.lean:55
#check BorceaVariance.Certificate.refined_distance_bound
-- BorceaVariance/Certificate/RetainedArithmetic.lean:13
#check BorceaVariance.Certificate.retained_half_value_bound
-- BorceaVariance/Certificate/RetainedArithmetic.lean:23
#check BorceaVariance.Certificate.retained_whole_value_bound
-- BorceaVariance/Certificate/RetainedArithmetic.lean:33
#check BorceaVariance.Certificate.retained_half_hull_continuous
-- BorceaVariance/Certificate/RetainedArithmetic.lean:40
#check BorceaVariance.Certificate.retained_whole_hull_continuous
-- BorceaVariance/Certificate/RetainedEnvelopes.lean:14
#check BorceaVariance.Certificate.retainedBase_cast
-- BorceaVariance/Certificate/RetainedEnvelopes.lean:18
#check BorceaVariance.Certificate.retained_base_convex
-- BorceaVariance/Certificate/RetainedEnvelopes.lean:25
#check BorceaVariance.Certificate.retained_base_continuous
-- BorceaVariance/Certificate/RetainedEnvelopes.lean:30
#check BorceaVariance.Certificate.retained_half_block_bound
-- BorceaVariance/Certificate/RetainedEnvelopes.lean:41
#check BorceaVariance.Certificate.retained_whole_block_bound
-- BorceaVariance/Certificate/RetainedEnvelopes.lean:47
#check BorceaVariance.Certificate.retained_half_hull_convex
-- BorceaVariance/Certificate/RetainedEnvelopes.lean:63
#check BorceaVariance.Certificate.retained_whole_hull_convex
-- BorceaVariance/Certificate/RetainedEnvelopes.lean:76
#check BorceaVariance.Certificate.retained_factor_moment_lower
-- BorceaVariance/Certificate/RetainedPointwise.lean:8
#check BorceaVariance.Certificate.retainedDelta_cast
-- BorceaVariance/Certificate/RetainedPointwise.lean:12
#check BorceaVariance.Certificate.retained_box_pointwise
-- BorceaVariance/Certificate/RetainedQuadrature.lean:28
#check BorceaVariance.Certificate.retained_segment_bound
-- BorceaVariance/Certificate/RetainedQuadrature.lean:103
#check BorceaVariance.Certificate.retained_quadrature_bound
-- BorceaVariance/Certificate/RootBounds.lean:26
#check BorceaVariance.Certificate.rootBUpper_bound
-- BorceaVariance/Certificate/RootBounds.lean:42
#check BorceaVariance.Certificate.rootCUpper_bound
-- BorceaVariance/Certificate/RootBounds.lean:61
#check BorceaVariance.Certificate.rootGap_lower
-- BorceaVariance/Certificate/RootBounds.lean:89
#check BorceaVariance.Certificate.root_defect_factor
-- BorceaVariance/Certificate/RootBounds.lean:101
#check BorceaVariance.Certificate.rootGammaLower_nonneg
-- BorceaVariance/Certificate/RootBounds.lean:108
#check BorceaVariance.Certificate.rootProductLower_bound
-- BorceaVariance/Certificate/RoundedConstants.lean:17
#check BorceaVariance.Certificate.omission_rounded_bounds
-- BorceaVariance/Certificate/RoundedCore.lean:22
#check BorceaVariance.Certificate.phi_box_argument
-- BorceaVariance/Certificate/RoundedCore.lean:27
#check BorceaVariance.Certificate.phiRounded_bounds
-- BorceaVariance/Certificate/RoundedCore.lean:45
#check BorceaVariance.Certificate.coreRounded_upper
-- BorceaVariance/Certificate/RoundedCore.lean:56
#check BorceaVariance.Certificate.normalized_core_rounded
-- BorceaVariance/Certificate/RoundedEndpoint.lean:7
#check BorceaVariance.Certificate.upperSqrt_encloses_norm
-- BorceaVariance/Certificate/RoundedEndpoint.lean:15
#check BorceaVariance.Certificate.upperHalfPower_encloses_norm_pow
-- BorceaVariance/Certificate/ScaledMesh.lean:7
#check BorceaVariance.Certificate.segment_majorant_one_scaled
-- BorceaVariance/Certificate/ScaledMesh.lean:25
#check BorceaVariance.Certificate.segment_majorant_two_scaled
-- BorceaVariance/Certificate/StableCore.lean:7
#check BorceaVariance.Certificate.secondMoment_half_box_upper
-- BorceaVariance/Certificate/StableCore.lean:24
#check BorceaVariance.Certificate.core_box_with_loss
-- BorceaVariance/Certificate/StableCore.lean:62
#check BorceaVariance.Certificate.taylor32_one_le
-- BorceaVariance/Certificate/StableCore.lean:74
#check BorceaVariance.Certificate.stable_core_rounded
-- BorceaVariance/Certificate/Tree.lean:5
#check BorceaVariance.Certificate.Interval.split_covers
-- BorceaVariance/Certificate/Tree.lean:11
#check BorceaVariance.Certificate.Box.split_covers
-- BorceaVariance/Certificate/Tree.lean:36
#check BorceaVariance.Certificate.Tree.coverage
-- BorceaVariance/Certificate/Tree.lean:46
#check BorceaVariance.Certificate.Tree.exclusion
-- BorceaVariance/CompactBounds.lean:9
#check BorceaVariance.compact_moment_bounds
-- BorceaVariance/CompactBounds.lean:31
#check BorceaVariance.norm_product_bound_of_secondMoment
-- BorceaVariance/CompactBounds.lean:44
#check BorceaVariance.direct_linear_integral_bound
-- BorceaVariance/Compactness.lean:9
#check BorceaVariance.normalized_compact
-- BorceaVariance/CoreProduct.lean:7
#check BorceaVariance.phi_base_nonneg_of_energy
-- BorceaVariance/CoreProduct.lean:18
#check BorceaVariance.root_product_upper
-- BorceaVariance/CoreProduct.lean:32
#check BorceaVariance.normalized_root_product_upper
-- BorceaVariance/CoreProduct.lean:47
#check BorceaVariance.normalized_core_product
-- BorceaVariance/CriticalPoints.lean:9
#check BorceaVariance.critical_root_sum_zero
-- BorceaVariance/CriticalPoints.lean:25
#check BorceaVariance.multiset_fin_enumeration
-- BorceaVariance/CriticalPoints.lean:31
#check BorceaVariance.normalized_critical_points
-- BorceaVariance/Definitions.lean:21
#check BorceaVariance.sigma2_nonneg
-- BorceaVariance/Definitions.lean:23
#check BorceaVariance.variance_nonneg
-- BorceaVariance/Definitions.lean:30
#check BorceaVariance.sigma2_sq
-- BorceaVariance/Degenerate.lean:6
#check BorceaVariance.root_eq_centroid_of_variance_zero
-- BorceaVariance/Degenerate.lean:21
#check BorceaVariance.polynomial_of_variance_zero
-- BorceaVariance/Degenerate.lean:32
#check BorceaVariance.zero_variance_main
-- BorceaVariance/Degenerate.lean:44
#check BorceaVariance.sigma2_pos_of_counterexample
-- BorceaVariance/ExponentialSeries.lean:9
#check BorceaVariance.exponential_series_bounds
-- BorceaVariance/FiniteCoordinates.lean:7
#check BorceaVariance.normalized_other_roots
-- BorceaVariance/FiniteCoordinates.lean:22
#check BorceaVariance.normalized_derivative_factorization
-- BorceaVariance/FiniteCoordinates.lean:31
#check BorceaVariance.normalized_product_identity
-- BorceaVariance/FiniteDegree.lean:14
#check BorceaVariance.Certificate.Generated.all_certificate_blocks_exclusion
-- BorceaVariance/FiniteDegree.lean:93
#check BorceaVariance.Certificate.Generated.finite_initialBox_exclusion
-- BorceaVariance/FiniteDegree.lean:104
#check BorceaVariance.no_normalized_counterexample_finite
-- BorceaVariance/FiniteDegree.lean:109
#check BorceaVariance.finite_degree_main
-- BorceaVariance/FiniteIdentities.lean:11
#check BorceaVariance.normalized_origin_identity_fin
-- BorceaVariance/FiniteIdentities.lean:28
#check BorceaVariance.normalized_center_identity_fin
-- BorceaVariance/FiniteMoments.lean:11
#check BorceaVariance.centered_sum
-- BorceaVariance/FiniteMoments.lean:14
#check BorceaVariance.sum_eq_card_mul_mean
-- BorceaVariance/FiniteMoments.lean:21
#check BorceaVariance.sum_sq_eq_card_mul_secondMoment
-- BorceaVariance/FiniteMoments.lean:27
#check BorceaVariance.centered_variance_sum
-- BorceaVariance/FiniteMoments.lean:31
#check BorceaVariance.centeredVariance_nonneg
-- BorceaVariance/FiniteMoments.lean:38
#check BorceaVariance.weighted_complex_cauchy
-- BorceaVariance/FiniteMoments.lean:55
#check BorceaVariance.complex_cauchy
-- BorceaVariance/Identities.lean:17
#check BorceaVariance.origin_identity_multiset
-- BorceaVariance/Identities.lean:33
#check BorceaVariance.normalized_origin_identity
-- BorceaVariance/Identities.lean:53
#check BorceaVariance.differential_identity
-- BorceaVariance/Identities.lean:59
#check BorceaVariance.center_power_integral
-- BorceaVariance/Identities.lean:64
#check BorceaVariance.center_identity
-- BorceaVariance/Integral/AbsoluteTest.lean:15
#check BorceaVariance.centered_error_integral_bound
-- BorceaVariance/Integral/AbsoluteTest.lean:28
#check BorceaVariance.absolute_integral_test
-- BorceaVariance/Integral/BetaPolynomial.lean:8
#check BorceaVariance.beta_nat_succ_identity
-- BorceaVariance/Integral/BetaPolynomial.lean:30
#check BorceaVariance.integral_nat_beta
-- BorceaVariance/Integral/BlockPowers.lean:5
#check BorceaVariance.rpow_le_max_endpoint
-- BorceaVariance/Integral/BlockPowers.lean:12
#check BorceaVariance.retained_base_antitone_degree
-- BorceaVariance/Integral/BlockPowers.lean:22
#check BorceaVariance.retained_block_power_bound
-- BorceaVariance/Integral/BlockPowers.lean:32
#check BorceaVariance.retained_block_nat_power_bound
-- BorceaVariance/Integral/CenteredFirst.lean:8
#check BorceaVariance.centered_first_remainder_general
-- BorceaVariance/Integral/CenteredFirst.lean:59
#check BorceaVariance.centered_first_remainder_moments
-- BorceaVariance/Integral/CenteredFirst.lean:77
#check BorceaVariance.centered_interpolation_first
-- BorceaVariance/Integral/CenteredSecond.lean:8
#check BorceaVariance.centered_second_remainder_general
-- BorceaVariance/Integral/CenteredSecond.lean:70
#check BorceaVariance.centered_second_remainder_moments
-- BorceaVariance/Integral/CenteredSecond.lean:91
#check BorceaVariance.centered_interpolation_second
-- BorceaVariance/Integral/Constants.lean:5
#check BorceaVariance.omissionConstant_sq_le_exp
-- BorceaVariance/Integral/Constants.lean:25
#check BorceaVariance.omission_one_constant_bounds
-- BorceaVariance/Integral/Constants.lean:33
#check BorceaVariance.omission_two_constant_bounds
-- BorceaVariance/Integral/ConvexMajorants.lean:6
#check BorceaVariance.convex_quadratic_majorant
-- BorceaVariance/Integral/ConvexMajorants.lean:20
#check BorceaVariance.convex_linear_majorant
-- BorceaVariance/Integral/ConvexMajorants.lean:30
#check BorceaVariance.convex_nonnegative_rpow
-- BorceaVariance/Integral/ConvexMajorants.lean:40
#check BorceaVariance.convex_positive_part
-- BorceaVariance/Integral/ConvexMajorants.lean:44
#check BorceaVariance.convex_retained_base
-- BorceaVariance/Integral/ConvexMajorants.lean:54
#check BorceaVariance.convex_retained_block_powers
-- BorceaVariance/Integral/ConvexMesh.lean:7
#check BorceaVariance.chord_one
-- BorceaVariance/Integral/ConvexMesh.lean:23
#check BorceaVariance.chord_two
-- BorceaVariance/Integral/ConvexMesh.lean:40
#check BorceaVariance.le_min_of_separate_bounds
-- BorceaVariance/Integral/DirectBounds.lean:7
#check BorceaVariance.directMajorant_le_first_moment
-- BorceaVariance/Integral/DirectBounds.lean:20
#check BorceaVariance.direct_unit_bound
-- BorceaVariance/Integral/DirectBounds.lean:32
#check BorceaVariance.direct_second_moment_bound
-- BorceaVariance/Integral/DirectBounds.lean:56
#check BorceaVariance.direct_bound
-- BorceaVariance/Integral/DirectRetained.lean:9
#check BorceaVariance.weighted_deleted_product_bound
-- BorceaVariance/Integral/DirectRetained.lean:19
#check BorceaVariance.retained_factor_lower
-- BorceaVariance/Integral/DirectRetained.lean:33
#check BorceaVariance.direct_retained_bound
-- BorceaVariance/Integral/DirectRetained.lean:59
#check BorceaVariance.originErrorSum_norm_le_directMajorant
-- BorceaVariance/Integral/DirectTest.lean:8
#check BorceaVariance.originProduct_endpoint_bound
-- BorceaVariance/Integral/DirectTest.lean:20
#check BorceaVariance.originRemainder_norm_le_direct_integral
-- BorceaVariance/Integral/DirectTest.lean:37
#check BorceaVariance.origin_core_integral_bound
-- BorceaVariance/Integral/DirectTest.lean:53
#check BorceaVariance.direct_integral_test
-- BorceaVariance/Integral/IntegralPolynomial.lean:14
#check BorceaVariance.binomial_beta_identity
-- BorceaVariance/Integral/IntegralPolynomial.lean:25
#check BorceaVariance.binomial_linear_factor_expansion
-- BorceaVariance/Integral/IntegralPolynomial.lean:34
#check BorceaVariance.integral_polynomial_identity
-- BorceaVariance/Integral/IntegralPolynomial.lean:59
#check BorceaVariance.integralPolynomial_nonneg
-- BorceaVariance/Integral/IntegralPolynomial.lean:64
#check BorceaVariance.power_sum_integral_relation
-- BorceaVariance/Integral/InterpolationAlgebra.lean:11
#check BorceaVariance.interpolationPolynomial_derivative
-- BorceaVariance/Integral/InterpolationAlgebra.lean:23
#check BorceaVariance.interpolationPolynomial_second_derivative
-- BorceaVariance/Integral/InterpolationAlgebra.lean:40
#check BorceaVariance.interpolationPolynomial_derivative_zero
-- BorceaVariance/Integral/InterpolationAlgebra.lean:51
#check BorceaVariance.polynomial_taylor_second
-- BorceaVariance/Integral/InterpolationAlgebra.lean:72
#check BorceaVariance.ordered_pair_norm_sum_bound
-- BorceaVariance/Integral/InterpolationMoments.lean:6
#check BorceaVariance.centered_norm_le_factor_mean
-- BorceaVariance/Integral/InterpolationMoments.lean:15
#check BorceaVariance.centered_interpolation_second_moment
-- BorceaVariance/Integral/InterpolationMoments.lean:30
#check BorceaVariance.centered_interpolation_first_moment
-- BorceaVariance/Integral/LinearIntegral.lean:7
#check BorceaVariance.integral_beta_one
-- BorceaVariance/Integral/LinearIntegral.lean:18
#check BorceaVariance.integral_linear_power_upper
-- BorceaVariance/Integral/Maclaurin.lean:6
#check BorceaVariance.esymm_fin_card_pred
-- BorceaVariance/Integral/Maclaurin.lean:39
#check BorceaVariance.sum_deleted_prod_le_mean
-- BorceaVariance/Integral/Majorants.lean:10
#check BorceaVariance.factorMean_nonneg
-- BorceaVariance/Integral/Majorants.lean:13
#check BorceaVariance.factorMean_sq_le_beta
-- BorceaVariance/Integral/Majorants.lean:24
#check BorceaVariance.factorMean_endpoint_sq_le
-- BorceaVariance/Integral/Majorants.lean:45
#check BorceaVariance.factorMean_endpoint_le_kappa
-- BorceaVariance/Integral/Majorants.lean:56
#check BorceaVariance.factorMean_endpoint_sqrt_bound
-- BorceaVariance/Integral/Majorants.lean:68
#check BorceaVariance.factorMean_linear_majorant
-- BorceaVariance/Integral/Majorants.lean:90
#check BorceaVariance.originProduct_norm_le_second_moment
-- BorceaVariance/Integral/OmissionBounds.lean:10
#check BorceaVariance.omissionConstant_nonneg
-- BorceaVariance/Integral/OmissionBounds.lean:14
#check BorceaVariance.omissionConstant_sq
-- BorceaVariance/Integral/OmissionBounds.lean:20
#check BorceaVariance.pow_le_rpow_half_of_sq_le
-- BorceaVariance/Integral/OmissionBounds.lean:29
#check BorceaVariance.norm_subproduct_le_second_moment
-- BorceaVariance/Integral/OmissionBounds.lean:45
#check BorceaVariance.norm_subproduct_le_first_moment
-- BorceaVariance/Integral/PolynomialTests.lean:7
#check BorceaVariance.normalized_direct_integral_test
-- BorceaVariance/Integral/PolynomialTests.lean:24
#check BorceaVariance.normalized_absolute_integral_test
-- BorceaVariance/Integral/PolynomialTests.lean:45
#check BorceaVariance.normalized_ratio_integral_test
-- BorceaVariance/Integral/RatioTest.lean:8
#check BorceaVariance.ratio_scalar_test
-- BorceaVariance/Integral/RatioTest.lean:44
#check BorceaVariance.normalized_core_product_le_mean
-- BorceaVariance/Integral/RetainedProducts.lean:6
#check BorceaVariance.norm_prod_le_first_moment
-- BorceaVariance/Integral/RetainedProducts.lean:23
#check BorceaVariance.retained_deleted_second_moment
-- BorceaVariance/Integral/RetainedProducts.lean:45
#check BorceaVariance.retained_deleted_first_moment
-- BorceaVariance/LargeDegree/Away.lean:8
#check BorceaVariance.large_degree_remainder_coefficient
-- BorceaVariance/LargeDegree/Away.lean:15
#check BorceaVariance.remainder_gap_to_H
-- BorceaVariance/LargeDegree/Away.lean:22
#check BorceaVariance.normalized_away_estimates
-- BorceaVariance/LargeDegree/Away.lean:59
#check BorceaVariance.no_normalized_counterexample_large_away
-- BorceaVariance/LargeDegree/Basic.lean:8
#check BorceaVariance.normalized_critical_secondMoment_le_one
-- BorceaVariance/LargeDegree/Basic.lean:16
#check BorceaVariance.normalized_core_product_le_psi
-- BorceaVariance/LargeDegree/Basic.lean:34
#check BorceaVariance.direct_norm_test
-- BorceaVariance/LargeDegree/Basic.lean:47
#check BorceaVariance.normalized_large_direct
-- BorceaVariance/LargeDegree/Central.lean:8
#check BorceaVariance.central_endpoint_bound
-- BorceaVariance/LargeDegree/Central.lean:26
#check BorceaVariance.no_normalized_counterexample_large_central
-- BorceaVariance/LargeDegree/CentralConstants.lean:6
#check BorceaVariance.central_first_coefficient
-- BorceaVariance/LargeDegree/CentralConstants.lean:18
#check BorceaVariance.central_B_power
-- BorceaVariance/LargeDegree/CentralConstants.lean:28
#check BorceaVariance.central_second_coefficient
-- BorceaVariance/LargeDegree/CentralConstants.lean:58
#check BorceaVariance.central_endpoint_power
-- BorceaVariance/LargeDegree/CentralGeometry.lean:6
#check BorceaVariance.central_real_part_lower
-- BorceaVariance/LargeDegree/CentralGeometry.lean:16
#check BorceaVariance.central_beta_bounds
-- BorceaVariance/LargeDegree/CentralGeometry.lean:66
#check BorceaVariance.central_center_factor_lower
-- BorceaVariance/LargeDegree/CentralIntegrals.lean:8
#check BorceaVariance.centeredError_continuous
-- BorceaVariance/LargeDegree/CentralIntegrals.lean:13
#check BorceaVariance.central_first_integral_bound
-- BorceaVariance/LargeDegree/CentralIntegrals.lean:50
#check BorceaVariance.central_second_integral_bound
-- BorceaVariance/LargeDegree/CentralIntegrals.lean:80
#check BorceaVariance.central_centered_integral_bound
-- BorceaVariance/LargeDegree/CentralPointwise.lean:7
#check BorceaVariance.centeredError_factor_order
-- BorceaVariance/LargeDegree/CentralPointwise.lean:14
#check BorceaVariance.central_first_pointwise
-- BorceaVariance/LargeDegree/CentralPointwise.lean:61
#check BorceaVariance.central_second_pointwise
-- BorceaVariance/LargeDegree/Exponential.lean:8
#check BorceaVariance.originProduct_exp_bound
-- BorceaVariance/LargeDegree/Exponential.lean:16
#check BorceaVariance.originRemainder_exp_bound
-- BorceaVariance/LargeDegree/Exponential.lean:54
#check BorceaVariance.reciprocal_real_part_lower
-- BorceaVariance/LargeDegree/Gap.lean:8
#check BorceaVariance.largeDegreeGap_pos
-- BorceaVariance/LargeDegree/Gap.lean:12
#check BorceaVariance.reciprocal_beta_linear_gap
-- BorceaVariance/LargeDegree/Gap.lean:27
#check BorceaVariance.reciprocal_beta_largeDegreeGap
-- BorceaVariance/LargeDegree/Gap.lean:43
#check BorceaVariance.largeDegreeGap_ge_one_five_hundred
-- BorceaVariance/LargeDegree/LargeA.lean:8
#check BorceaVariance.large_a_moment_bounds
-- BorceaVariance/LargeDegree/LargeA.lean:31
#check BorceaVariance.no_normalized_counterexample_large_a_ge_two
-- BorceaVariance/LargeDegree/SmallA.lean:6
#check BorceaVariance.small_a_remainder_coefficient
-- BorceaVariance/LargeDegree/SmallA.lean:14
#check BorceaVariance.small_a_remainder_algebra
-- BorceaVariance/LargeDegree/SmallA.lean:20
#check BorceaVariance.no_normalized_counterexample_large_small_a
-- BorceaVariance/LargeDegree/SmallABounds.lean:7
#check BorceaVariance.normalized_degree_log_bound
-- BorceaVariance/LargeDegree/SmallABounds.lean:53
#check BorceaVariance.log_degree_gt_ten
-- BorceaVariance/LargeDegree/SmallABounds.lean:66
#check BorceaVariance.normalized_small_a_degree
-- BorceaVariance/LargeDegree/SmallABounds.lean:73
#check BorceaVariance.small_a_real_part_lower
-- BorceaVariance/LargeDegree/TableConstants.lean:7
#check BorceaVariance.large_degree_exponential_comparisons
-- BorceaVariance/LargeDegree/TableConstants.lean:32
#check BorceaVariance.psi_table_endpoints
-- BorceaVariance/LargeDegree/TableConstants.lean:58
#check BorceaVariance.psi_away_table
-- BorceaVariance/LargeDegree/TableConstants.lean:76
#check BorceaVariance.exp_neg_hundred_lt
-- BorceaVariance/LargeDegree/TableConstants.lean:83
#check BorceaVariance.exp_neg_small_a_lt
-- BorceaVariance/LargeDegree/TableH.lean:9
#check BorceaVariance.largeDegreeH_interval_bound
-- BorceaVariance/LargeDegree/TableH.lean:41
#check BorceaVariance.largeDegreeH_table
-- BorceaVariance/LargeDegree.lean:10
#check BorceaVariance.no_normalized_counterexample_large
-- BorceaVariance/LargeDegree.lean:26
#check BorceaVariance.large_degree_main
-- BorceaVariance/LargeDegreeConstants.lean:6
#check BorceaVariance.one_sub_le_exp_neg
-- BorceaVariance/LargeDegreeConstants.lean:9
#check BorceaVariance.exp_ge_sixth
-- BorceaVariance/LargeDegreeConstants.lean:13
#check BorceaVariance.small_a_final_margin
-- BorceaVariance/LargeDegreeConstants.lean:16
#check BorceaVariance.away_table_margins
-- BorceaVariance/LargeDegreeConstants.lean:23
#check BorceaVariance.central_B_value
-- BorceaVariance/LargeDegreeConstants.lean:25
#check BorceaVariance.near_final_rational_margin
-- BorceaVariance/LinearAlgebra/CharpolyDerivative.lean:11
#check BorceaVariance.polynomial_det_derivative
-- BorceaVariance/LinearAlgebra/CharpolyDerivative.lean:33
#check BorceaVariance.charpoly_derivative_columns
-- BorceaVariance/LinearAlgebra/CharpolyDerivative.lean:46
#check BorceaVariance.diagonal_cofactor_charpoly
-- BorceaVariance/LinearAlgebra/CirculantDerivative.lean:17
#check BorceaVariance.circulant_charmatrix_shift
-- BorceaVariance/LinearAlgebra/CirculantDerivative.lean:28
#check BorceaVariance.circulant_diagonal_cofactor_eq
-- BorceaVariance/LinearAlgebra/CirculantDerivative.lean:55
#check BorceaVariance.circulant_charpoly_derivative
-- BorceaVariance/LinearAlgebra/CirculantVariance.lean:10
#check BorceaVariance.circulant_row_sum
-- BorceaVariance/LinearAlgebra/CirculantVariance.lean:14
#check BorceaVariance.circulant_row_sum_isRoot
-- BorceaVariance/LinearAlgebra/CirculantVariance.lean:27
#check BorceaVariance.circulant_trace
-- BorceaVariance/LinearAlgebra/CirculantVariance.lean:31
#check BorceaVariance.circulant_centroid
-- BorceaVariance/LinearAlgebra/CirculantVariance.lean:39
#check BorceaVariance.circulant_frobenius
-- BorceaVariance/LinearAlgebra/CirculantVariance.lean:48
#check BorceaVariance.circulant_variance_le
-- BorceaVariance/LinearAlgebra/CollinearComplex.lean:7
#check BorceaVariance.complex_pair_conjugate_iff_real_line
-- BorceaVariance/LinearAlgebra/CollinearComplex.lean:30
#check BorceaVariance.centered_collinear_iff_real_line
-- BorceaVariance/LinearAlgebra/CollinearComplex.lean:64
#check BorceaVariance.centered_collinear_iff_pair_conjugate
-- BorceaVariance/LinearAlgebra/Compression.lean:18
#check BorceaVariance.compression_entry_norm
-- BorceaVariance/LinearAlgebra/Compression.lean:35
#check BorceaVariance.centered_pair_norm_sum
-- BorceaVariance/LinearAlgebra/Compression.lean:41
#check BorceaVariance.centered_compression_frobenius
-- BorceaVariance/LinearAlgebra/Compression.lean:55
#check BorceaVariance.uniformProjection_row_sum
-- BorceaVariance/LinearAlgebra/Compression.lean:60
#check BorceaVariance.compression_row_sum
-- BorceaVariance/LinearAlgebra/Compression.lean:70
#check BorceaVariance.uniformProjection_idempotent
-- BorceaVariance/LinearAlgebra/Compression.lean:82
#check BorceaVariance.centeredCompression_eq_projection_diagonal
-- BorceaVariance/LinearAlgebra/CompressionCharpoly.lean:7
#check BorceaVariance.charpoly_eval_projection_diagonal
-- BorceaVariance/LinearAlgebra/CompressionCharpoly.lean:28
#check BorceaVariance.root_product_derivative_eval
-- BorceaVariance/LinearAlgebra/CompressionCharpoly.lean:40
#check BorceaVariance.projection_diagonal_charpoly
-- BorceaVariance/LinearAlgebra/CompressionCharpoly.lean:66
#check BorceaVariance.centered_compression_charpoly
-- BorceaVariance/LinearAlgebra/CompressionNormal.lean:7
#check BorceaVariance.centered_compression_conjTranspose
-- BorceaVariance/LinearAlgebra/CompressionNormal.lean:15
#check BorceaVariance.centered_compression_mul_entry
-- BorceaVariance/LinearAlgebra/CompressionNormal.lean:37
#check BorceaVariance.centered_compression_commutator
-- BorceaVariance/LinearAlgebra/CompressionNormal.lean:53
#check BorceaVariance.centered_compression_normal_iff_pair
-- BorceaVariance/LinearAlgebra/DeterminantLemma.lean:8
#check BorceaVariance.det_diagonal_add_row
-- BorceaVariance/LinearAlgebra/Frobenius.lean:10
#check BorceaVariance.frobeniusSquare_eq_trace
-- BorceaVariance/LinearAlgebra/Frobenius.lean:16
#check BorceaVariance.frobeniusSquare_nonneg
-- BorceaVariance/LinearAlgebra/Frobenius.lean:20
#check BorceaVariance.frobeniusSquare_unitary_similarity
-- BorceaVariance/LinearAlgebra/Frobenius.lean:32
#check BorceaVariance.diagonal_energy_le_frobeniusSquare
-- BorceaVariance/LinearAlgebra/NormalBlocks.lean:7
#check BorceaVariance.unitary_normal_similarity_iff
-- BorceaVariance/LinearAlgebra/NormalBlocks.lean:32
#check BorceaVariance.first_block_normal_iff
-- BorceaVariance/LinearAlgebra/NormalBlocks.lean:54
#check BorceaVariance.first_column_row_of_frobenius_eq
-- BorceaVariance/LinearAlgebra/Normality.lean:7
#check BorceaVariance.normal_row_energy_eq_column_energy
-- BorceaVariance/LinearAlgebra/Normality.lean:15
#check BorceaVariance.first_column_normal_row
-- BorceaVariance/LinearAlgebra/Normality.lean:32
#check BorceaVariance.first_block_frobenius_eq
-- BorceaVariance/LinearAlgebra/Normality.lean:41
#check BorceaVariance.first_block_normal
-- BorceaVariance/LinearAlgebra/Schur.lean:8
#check BorceaVariance.schur_frobenius_bound
-- BorceaVariance/LinearAlgebra/SchurEquality.lean:7
#check BorceaVariance.schur_frobenius_eq_iff_normal
-- BorceaVariance/LinearAlgebra/SchurStep.lean:11
#check BorceaVariance.exists_orthonormal_eigenbasis_first
-- BorceaVariance/LinearAlgebra/SchurStep.lean:42
#check BorceaVariance.eigenbasis_first_column
-- BorceaVariance/LinearAlgebra/SchurStep.lean:52
#check BorceaVariance.orthonormal_change_matrix
-- BorceaVariance/LinearAlgebra/SchurStep.lean:72
#check BorceaVariance.first_column_charpoly
-- BorceaVariance/LinearAlgebra/SchurStep.lean:94
#check BorceaVariance.first_block_frobenius_le
-- BorceaVariance/LinearAlgebra/ToeplitzBridge.lean:9
#check BorceaVariance.circulant_critical_roots
-- BorceaVariance/LinearAlgebra/ToeplitzBridge.lean:17
#check BorceaVariance.circulant_critical_iff_toeplitz_root
-- BorceaVariance/LinearAlgebra/ToeplitzBridge.lean:27
#check BorceaVariance.matrix_root_eigenvector
-- BorceaVariance/LinearAlgebra/ToeplitzBridge.lean:36
#check BorceaVariance.circulant_critical_toeplitz_eigenvector
-- BorceaVariance/LinearAlgebra/ToeplitzBridge.lean:44
#check BorceaVariance.circulant_radius_to_squared_bound
-- BorceaVariance/Main.lean:10
#check BorceaVariance.main_theorem
-- BorceaVariance/Main.lean:20
#check BorceaVariance.main_statement
-- BorceaVariance/Normalization.lean:20
#check BorceaVariance.exists_normalizing_scale
-- BorceaVariance/Normalization.lean:40
#check BorceaVariance.normalize_counterexample
-- BorceaVariance/Normalization.lean:95
#check BorceaVariance.normalized_root_factorization
-- BorceaVariance/PhiMonotonicity.lean:7
#check BorceaVariance.phi_succ_mono
-- BorceaVariance/PhiMonotonicity.lean:34
#check BorceaVariance.phi_base_nonneg_of_degree
-- BorceaVariance/PhiMonotonicity.lean:43
#check BorceaVariance.phi_mono_degree
-- BorceaVariance/PhiShape.lean:9
#check BorceaVariance.hasDerivAt_phiSquareKernel
-- BorceaVariance/PhiShape.lean:29
#check BorceaVariance.phi_mono_before_one
-- BorceaVariance/PhiShape.lean:56
#check BorceaVariance.phi_antitone_after_one
-- BorceaVariance/PolynomialBasics.lean:10
#check BorceaVariance.eval_affinePullback
-- BorceaVariance/PolynomialBasics.lean:14
#check BorceaVariance.natDegree_affinePullback
-- BorceaVariance/PolynomialBasics.lean:18
#check BorceaVariance.derivative_affinePullback
-- BorceaVariance/PolynomialBasics.lean:24
#check BorceaVariance.roots_affinePullback
-- BorceaVariance/PolynomialBasics.lean:29
#check BorceaVariance.critical_roots_affinePullback
-- BorceaVariance/PolynomialBasics.lean:34
#check BorceaVariance.roots_card
-- BorceaVariance/PolynomialBasics.lean:37
#check BorceaVariance.multiset_sum_affine
-- BorceaVariance/PolynomialBasics.lean:46
#check BorceaVariance.centroid_affinePullback
-- BorceaVariance/PolynomialBasics.lean:55
#check BorceaVariance.centroid_C_mul
-- BorceaVariance/PolynomialBasics.lean:59
#check BorceaVariance.variance_C_mul
-- BorceaVariance/PolynomialBasics.lean:63
#check BorceaVariance.sigma2_C_mul
-- BorceaVariance/PolynomialBasics.lean:67
#check BorceaVariance.variance_affinePullback
-- BorceaVariance/PolynomialBasics.lean:84
#check BorceaVariance.sigma2_affinePullback
-- BorceaVariance/PolynomialMoments.lean:8
#check BorceaVariance.actual_critical_family_centered
-- BorceaVariance/PolynomialMoments.lean:17
#check BorceaVariance.actual_critical_family_far
-- BorceaVariance/PolynomialMoments.lean:27
#check BorceaVariance.normalized_reciprocal_moments
-- BorceaVariance/PolynomialMoments.lean:45
#check BorceaVariance.normalized_distinguished_pos
-- BorceaVariance/PsiShape.lean:7
#check BorceaVariance.hasDerivAt_psi
-- BorceaVariance/PsiShape.lean:13
#check BorceaVariance.psi_mono_before_one
-- BorceaVariance/PsiShape.lean:25
#check BorceaVariance.psi_antitone_after_one
-- BorceaVariance/PsiShape.lean:37
#check BorceaVariance.psi_two_lt
-- BorceaVariance/ReciprocalAlgebra.lean:12
#check BorceaVariance.reciprocal_mul
-- BorceaVariance/ReciprocalAlgebra.lean:16
#check BorceaVariance.reciprocal_norm_lt_one
-- BorceaVariance/ReciprocalAlgebra.lean:22
#check BorceaVariance.reciprocal_ne_zero
-- BorceaVariance/ReciprocalAlgebra.lean:26
#check BorceaVariance.reciprocal_conjugate_formula
-- BorceaVariance/ReciprocalAlgebra.lean:41
#check BorceaVariance.reciprocal_product_identity
-- BorceaVariance/ReciprocalAlgebra.lean:47
#check BorceaVariance.sum_beta
-- BorceaVariance/ReciprocalAlgebra.lean:53
#check BorceaVariance.beta_decomposition
-- BorceaVariance/ReciprocalAlgebra.lean:61
#check BorceaVariance.beta_nonneg
-- BorceaVariance/ReciprocalAlgebra.lean:66
#check BorceaVariance.secondMoment_reciprocal_lt_one
-- BorceaVariance/ReciprocalAlgebra.lean:81
#check BorceaVariance.secondMoment_reciprocal_pos
-- BorceaVariance/ReciprocalAlgebra.lean:92
#check BorceaVariance.centered_shift_energy
-- BorceaVariance/ReciprocalAlgebra.lean:101
#check BorceaVariance.reciprocal_weight_sum
-- BorceaVariance/ReciprocalAlgebra.lean:108
#check BorceaVariance.reciprocal_weighted_energy
-- BorceaVariance/ReciprocalAlgebra.lean:128
#check BorceaVariance.reciprocal_weighted_identity
-- BorceaVariance/ReciprocalAlgebra.lean:150
#check BorceaVariance.reciprocal_centered_identity
-- BorceaVariance/ReciprocalMoments.lean:6
#check BorceaVariance.norm_sub_real_sq
-- BorceaVariance/ReciprocalMoments.lean:12
#check BorceaVariance.norm_one_sub_real_mul_sq
-- BorceaVariance/ReciprocalMoments.lean:19
#check BorceaVariance.reciprocal_weighted_cauchy
-- BorceaVariance/ReciprocalMoments.lean:46
#check BorceaVariance.reciprocal_moment_A
-- BorceaVariance/ReciprocalMoments.lean:59
#check BorceaVariance.reciprocal_moment_A_distance
-- BorceaVariance/ReciprocalMoments.lean:68
#check BorceaVariance.reciprocal_moment_B
-- BorceaVariance/ReciprocalMoments.lean:85
#check BorceaVariance.reciprocal_inverse_moment
-- BorceaVariance/ReciprocalMoments.lean:105
#check BorceaVariance.reciprocal_moment_endpoint
-- BorceaVariance/ReciprocalMoments.lean:117
#check BorceaVariance.reciprocal_moments
-- BorceaVariance/RootGeometry.lean:7
#check BorceaVariance.normalized_degree_bound
-- BorceaVariance/Schoenberg.lean:9
#check BorceaVariance.schoenberg_centered_monic
-- BorceaVariance/Schoenberg.lean:45
#check BorceaVariance.schoenberg_centered
-- BorceaVariance/Schoenberg.lean:62
#check BorceaVariance.normalized_critical_energy_bound
-- BorceaVariance/Schoenberg.lean:71
#check BorceaVariance.normalized_critical_secondMoment_bound
-- BorceaVariance/SchoenbergEquality.lean:10
#check BorceaVariance.schoenberg_centered_monic_equality
-- BorceaVariance/SchoenbergEquality.lean:53
#check BorceaVariance.schoenberg_centered_equality
-- BorceaVariance/Sharpness.lean:8
#check BorceaVariance.sharpPolynomial_degree
-- BorceaVariance/Sharpness.lean:12
#check BorceaVariance.sharpPolynomial_root_norm
-- BorceaVariance/Sharpness.lean:18
#check BorceaVariance.sharpPolynomial_centroid
-- BorceaVariance/Sharpness.lean:34
#check BorceaVariance.sharpPolynomial_sigma2
-- BorceaVariance/Sharpness.lean:50
#check BorceaVariance.sharpPolynomial_critical_iff
-- BorceaVariance/Sharpness.lean:56
#check BorceaVariance.sharpness_family
-- BorceaVariance/Sharpness.lean:66
#check BorceaVariance.constant_one_sharp
-- BorceaVariance/SmallDegree/CoefficientBounds.lean:9
#check BorceaVariance.iterated_derivative_leadingCoeff
-- BorceaVariance/SmallDegree/CoefficientBounds.lean:17
#check BorceaVariance.iterated_derivative_root_product
-- BorceaVariance/SmallDegree/CoefficientBounds.lean:40
#check BorceaVariance.polynomial_root_energy_nonneg
-- BorceaVariance/SmallDegree/CoefficientBounds.lean:47
#check BorceaVariance.centered_polynomial_esymm_bound
-- BorceaVariance/SmallDegree/CoefficientBounds.lean:92
#check BorceaVariance.centered_family_esymm_bound
-- BorceaVariance/SmallDegree/CoefficientBounds.lean:119
#check BorceaVariance.centered_coefficients
-- BorceaVariance/SmallDegree/CoefficientIntegral.lean:8
#check BorceaVariance.centered_error_coefficient_bound
-- BorceaVariance/SmallDegree/CoefficientIntegral.lean:25
#check BorceaVariance.centered_error_integral_coefficient_bound
-- BorceaVariance/SmallDegree/CoefficientIntegral.lean:53
#check BorceaVariance.pow_mul_half_rpow
-- BorceaVariance/SmallDegree/CoefficientIntegral.lean:64
#check BorceaVariance.coefficient_error_integral_bound
-- BorceaVariance/SmallDegree/CoefficientTail.lean:11
#check BorceaVariance.tail_coefficient_bound
-- BorceaVariance/SmallDegree/CoefficientTail.lean:28
#check BorceaVariance.tail_integral_coefficient_bound
-- BorceaVariance/SmallDegree/CoefficientTail.lean:56
#check BorceaVariance.coefficient_tail_integral_bound
-- BorceaVariance/SmallDegree/CoefficientTest.lean:8
#check BorceaVariance.center_integral_norm_test
-- BorceaVariance/SmallDegree/CoefficientTest.lean:42
#check BorceaVariance.coefficient_integral_test
-- BorceaVariance/SmallDegree/CoefficientTest.lean:56
#check BorceaVariance.normalized_coefficient_integral_test
-- BorceaVariance/SmallDegree/ConvexPacking.lean:8
#check BorceaVariance.convex_pair_sum_upper
-- BorceaVariance/SmallDegree/ConvexPacking.lean:36
#check BorceaVariance.convex_packing_exists
-- BorceaVariance/SmallDegree/ConvexPacking.lean:63
#check BorceaVariance.convex_packing_zero
-- BorceaVariance/SmallDegree/ConvexPacking.lean:93
#check BorceaVariance.convex_packing
-- BorceaVariance/SmallDegree/Cubic.lean:9
#check BorceaVariance.no_normalized_counterexample_cubic
-- BorceaVariance/SmallDegree/Cubic.lean:46
#check BorceaVariance.cubic_main
-- BorceaVariance/SmallDegree/CubicGeometry.lean:6
#check BorceaVariance.complex_quadratic_norm_identity
-- BorceaVariance/SmallDegree/CubicGeometry.lean:15
#check BorceaVariance.choose_signed_critical_point
-- BorceaVariance/SmallDegree/CubicGeometry.lean:28
#check BorceaVariance.cubic_two_point_bound
-- BorceaVariance/SmallDegree/InverseRoots.lean:7
#check BorceaVariance.normalized_root_distances_ne_zero
-- BorceaVariance/SmallDegree/InverseRoots.lean:23
#check BorceaVariance.normalized_critical_logderivative
-- BorceaVariance/SmallDegree/InverseRoots.lean:40
#check BorceaVariance.normalized_inverse_root_sum
-- BorceaVariance/SmallDegree/InverseRoots.lean:67
#check BorceaVariance.normalized_inverse_root_mean
-- BorceaVariance/SmallDegree/IteratedSchoenberg.lean:7
#check BorceaVariance.complex_natDegree_iterate_derivative
-- BorceaVariance/SmallDegree/IteratedSchoenberg.lean:15
#check BorceaVariance.iterated_critical_root_sum_zero
-- BorceaVariance/SmallDegree/IteratedSchoenberg.lean:27
#check BorceaVariance.iterated_schoenberg
-- BorceaVariance/SmallDegree/LogarithmicPacking.lean:9
#check BorceaVariance.packing_power_interval_exists
-- BorceaVariance/SmallDegree/LogarithmicPacking.lean:42
#check BorceaVariance.packing_residual_bounds
-- BorceaVariance/SmallDegree/LogarithmicPacking.lean:52
#check BorceaVariance.logarithmic_convex_packing
-- BorceaVariance/SmallDegree/LogLoss.lean:11
#check BorceaVariance.hasDerivAt_logLossKernel
-- BorceaVariance/SmallDegree/LogLoss.lean:18
#check BorceaVariance.log_loss
-- BorceaVariance/SmallDegree/LogLoss.lean:62
#check BorceaVariance.finite_log_loss
-- BorceaVariance/SmallDegree/LogLoss.lean:77
#check BorceaVariance.finite_product_radial_loss
-- BorceaVariance/SmallDegree/NearEquality.lean:11
#check BorceaVariance.near_final_impossible
-- BorceaVariance/SmallDegree/NearEquality.lean:23
#check BorceaVariance.no_normalized_counterexample_near_uniform
-- BorceaVariance/SmallDegree/NearGeometry.lean:7
#check BorceaVariance.near_mean_variance_bounds
-- BorceaVariance/SmallDegree/NearGeometry.lean:21
#check BorceaVariance.near_radial_distance
-- BorceaVariance/SmallDegree/NearGeometry.lean:49
#check BorceaVariance.near_complex_controls
-- BorceaVariance/SmallDegree/NearKernel.lean:7
#check BorceaVariance.integralPowerSum_zero
-- BorceaVariance/SmallDegree/NearKernel.lean:15
#check BorceaVariance.quadraticKernel_one
-- BorceaVariance/SmallDegree/NearKernel.lean:30
#check BorceaVariance.near_kernel_integrand
-- BorceaVariance/SmallDegree/NearKernel.lean:61
#check BorceaVariance.quadraticKernel_near_one
-- BorceaVariance/SmallDegree/NearPowerSum.lean:6
#check BorceaVariance.integralPowerSum_mono
-- BorceaVariance/SmallDegree/NearPowerSum.lean:13
#check BorceaVariance.integralPowerSum_nonneg
-- BorceaVariance/SmallDegree/NearPowerSum.lean:19
#check BorceaVariance.near_integralPowerSum
-- BorceaVariance/SmallDegree/NearQuadratic.lean:7
#check BorceaVariance.near_kernel_one_bounds
-- BorceaVariance/SmallDegree/NearQuadratic.lean:20
#check BorceaVariance.near_kernel_phase_bound
-- BorceaVariance/SmallDegree/NearQuadratic.lean:56
#check BorceaVariance.near_quadratic_lower
-- BorceaVariance/SmallDegree/NearTail.lean:8
#check BorceaVariance.rpow_half_le_of_sq
-- BorceaVariance/SmallDegree/NearTail.lean:18
#check BorceaVariance.near_tau_bounds
-- BorceaVariance/SmallDegree/NearTail.lean:39
#check BorceaVariance.near_geometric_tail
-- BorceaVariance/SmallDegree/NearTail.lean:57
#check BorceaVariance.near_coefficient_sum
-- BorceaVariance/SmallDegree/NearTail.lean:101
#check BorceaVariance.near_tail_integral
-- BorceaVariance/SmallDegree/Packing.lean:8
#check BorceaVariance.reciprocal_packing_pointwise
-- BorceaVariance/SmallDegree/Packing.lean:18
#check BorceaVariance.finite_packing_distance_sum
-- BorceaVariance/SmallDegree/Packing.lean:45
#check BorceaVariance.finite_packing_inverse_sum
-- BorceaVariance/SmallDegree/Packing.lean:68
#check BorceaVariance.reciprocal_packing_distance
-- BorceaVariance/SmallDegree/Packing.lean:83
#check BorceaVariance.reciprocal_packing_variance
-- BorceaVariance/SmallDegree/Packing.lean:103
#check BorceaVariance.reciprocal_packing
-- BorceaVariance/SmallDegree/PackingFunctions.lean:12
#check BorceaVariance.hasDerivAt_packingDefect
-- BorceaVariance/SmallDegree/PackingFunctions.lean:17
#check BorceaVariance.hasDerivAt_packingDefect_deriv
-- BorceaVariance/SmallDegree/PackingFunctions.lean:22
#check BorceaVariance.packingDefect_convex
-- BorceaVariance/SmallDegree/PackingFunctions.lean:33
#check BorceaVariance.packingDefect_monotone
-- BorceaVariance/SmallDegree/PackingFunctions.lean:38
#check BorceaVariance.packingDefect_neg_log
-- BorceaVariance/SmallDegree/PackingFunctions.lean:50
#check BorceaVariance.packing_exp_neg_log
-- BorceaVariance/SmallDegree/PackingPointwise.lean:13
#check BorceaVariance.hasDerivAt_packingKernel
-- BorceaVariance/SmallDegree/PackingPointwise.lean:36
#check BorceaVariance.packingKernel_monotone
-- BorceaVariance/SmallDegree/PackingPointwise.lean:51
#check BorceaVariance.packing_product_upper
-- BorceaVariance/SmallDegree/PackingPointwise.lean:77
#check BorceaVariance.packing_pointwise_lower
-- BorceaVariance/SmallDegree/Phase.lean:12
#check BorceaVariance.meanPhase_scale
-- BorceaVariance/SmallDegree/Phase.lean:19
#check BorceaVariance.mean_phase_integral_bound
-- BorceaVariance/SmallDegree/Phase.lean:30
#check BorceaVariance.quadratic_phase_signed_lower
-- BorceaVariance/SmallDegree/Phase.lean:47
#check BorceaVariance.signed_coefficient_integral_test
-- BorceaVariance/SmallDegree/Phase.lean:69
#check BorceaVariance.normalized_signed_coefficient_test
-- BorceaVariance/SmallDegree/PhaseIntegrand.lean:9
#check BorceaVariance.complex_pow_difference_bound
-- BorceaVariance/SmallDegree/PhaseIntegrand.lean:32
#check BorceaVariance.unit_cube_difference_bound
-- BorceaVariance/SmallDegree/PhaseIntegrand.lean:36
#check BorceaVariance.phase_integrand_bound
-- BorceaVariance/SmallDegree/PhaseKernel.lean:13
#check BorceaVariance.quadraticKernel_real
-- BorceaVariance/SmallDegree/PhaseKernel.lean:26
#check BorceaVariance.realQuadraticKernel_nonneg
-- BorceaVariance/SmallDegree/PhaseKernel.lean:31
#check BorceaVariance.phase_integral_bound
-- BorceaVariance/SmallDegree/ProductExpansion.lean:8
#check BorceaVariance.elementarySymmetric_zero
-- BorceaVariance/SmallDegree/ProductExpansion.lean:12
#check BorceaVariance.elementarySymmetric_one
-- BorceaVariance/SmallDegree/ProductExpansion.lean:17
#check BorceaVariance.elementarySymmetric_mul
-- BorceaVariance/SmallDegree/ProductExpansion.lean:23
#check BorceaVariance.finite_product_expansion
-- BorceaVariance/SmallDegree/ProductExpansion.lean:37
#check BorceaVariance.centered_product_expansion
-- BorceaVariance/SmallDegree/ProductExpansion.lean:49
#check BorceaVariance.origin_centered_product_expansion
-- BorceaVariance/SmallDegree/ProductExpansion.lean:66
#check BorceaVariance.center_linear_factor_bound
-- BorceaVariance/SmallDegree/Quadratic.lean:7
#check BorceaVariance.quadratic_main
-- BorceaVariance/SmallDegree/QuadraticReal.lean:8
#check BorceaVariance.elementarySymmetric_two_identity
-- BorceaVariance/SmallDegree/QuadraticReal.lean:27
#check BorceaVariance.centered_elementarySymmetric_two
-- BorceaVariance/SmallDegree/QuadraticReal.lean:34
#check BorceaVariance.centered_elementarySymmetric_two_real
-- BorceaVariance/SmallDegree/QuadraticReal.lean:51
#check BorceaVariance.rotateToMean_centered
-- BorceaVariance/SmallDegree/QuadraticReal.lean:57
#check BorceaVariance.rotated_centered_energy
-- BorceaVariance/SmallDegree/QuadraticReal.lean:66
#check BorceaVariance.rotated_quadratic_real
-- BorceaVariance/SmallDegree/QuadraticSign.lean:10
#check BorceaVariance.meanPhase_norm
-- BorceaVariance/SmallDegree/QuadraticSign.lean:15
#check BorceaVariance.meanPhase_centered
-- BorceaVariance/SmallDegree/QuadraticSign.lean:21
#check BorceaVariance.elementarySymmetric_meanPhase
-- BorceaVariance/SmallDegree/QuadraticSign.lean:31
#check BorceaVariance.centered_quadratic_norm
-- BorceaVariance/SmallDegree/QuadraticSign.lean:41
#check BorceaVariance.rotated_quadratic_norm
-- BorceaVariance/SmallDegree/QuadraticSign.lean:51
#check BorceaVariance.real_product_perturbation_lower
-- BorceaVariance/SmallDegree/QuadraticSign.lean:62
#check BorceaVariance.quadratic_signed_lower
-- BorceaVariance/SmallDegree/QuadraticSplit.lean:9
#check BorceaVariance.centered_error_quadratic_split
-- BorceaVariance/SmallDegree/QuadraticSplit.lean:21
#check BorceaVariance.centered_error_quadratic_integral
-- BorceaVariance/SmallDegree/QuadraticSplit.lean:41
#check BorceaVariance.signed_center_identity
-- BorceaVariance/SmallDegree/QuadraticSplit.lean:54
#check BorceaVariance.signed_integral_norm_test
-- BorceaVariance/SmallDegree/Quartic.lean:7
#check BorceaVariance.no_normalized_counterexample_four
-- BorceaVariance/SmallDegree/Quartic.lean:13
#check BorceaVariance.quartic_main
-- BorceaVariance/SmallDegree/RadialBounds.lean:6
#check BorceaVariance.inverse_conjugate_eq_defect_mul_inv
-- BorceaVariance/SmallDegree/RadialBounds.lean:15
#check BorceaVariance.reciprocal_inverse_error_norm
-- BorceaVariance/SmallDegree/RadialBounds.lean:32
#check BorceaVariance.reciprocal_sq_lower
-- BorceaVariance/SmallDegree/RadialBounds.lean:43
#check BorceaVariance.finite_radial_mean_bound
-- BorceaVariance/SmallDegree/RadialBounds.lean:94
#check BorceaVariance.finite_radial_variance_bound
-- BorceaVariance/SmallDegree/RadialBounds.lean:140
#check BorceaVariance.product_radial_bound
-- BorceaVariance/SmallDegree/RadialBounds.lean:167
#check BorceaVariance.product_radial_sqrt_bound
-- BorceaVariance/SmallDegree/RadialBounds.lean:177
#check BorceaVariance.product_radial_square_bound
-- BorceaVariance/SmallDegree/RadialLoss.lean:7
#check BorceaVariance.reciprocal_radial_covariance
-- BorceaVariance/SmallDegree/RadialLoss.lean:28
#check BorceaVariance.reciprocal_radial_variance_lower
-- BorceaVariance/SmallDegree/RadialLoss.lean:54
#check BorceaVariance.reciprocal_radial_loss
-- BorceaVariance/SmallDegree/RadialLoss.lean:88
#check BorceaVariance.reciprocal_product_amgm
-- BorceaVariance/SmallDegree/RealCoordinateVariance.lean:17
#check BorceaVariance.rotateToMean_norm
-- BorceaVariance/SmallDegree/RealCoordinateVariance.lean:23
#check BorceaVariance.rotateToMean_sum
-- BorceaVariance/SmallDegree/RealCoordinateVariance.lean:29
#check BorceaVariance.finite_real_coordinate_lower
-- BorceaVariance/SmallDegree/RealCoordinateVariance.lean:63
#check BorceaVariance.finite_real_variance_of_bounds
-- BorceaVariance/SmallDegree/RealCoordinateVariance.lean:83
#check BorceaVariance.finite_real_variance_bound
-- BorceaVariance/SmallDegree/RealCoordinateVariance.lean:96
#check BorceaVariance.rotated_real_variance_bound
-- BorceaVariance/SmallDegree/RealVariance.lean:8
#check BorceaVariance.bhatia_davis
-- BorceaVariance/SmallDegree/RootCovariance.lean:6
#check BorceaVariance.inverse_root_centered_sum
-- BorceaVariance/SmallDegree/RootCovariance.lean:22
#check BorceaVariance.inverse_root_cauchy
-- BorceaVariance/SmallDegree/RootCovariance.lean:35
#check BorceaVariance.real_sub_mul_norm_identity
-- BorceaVariance/SmallDegree/RootCovariance.lean:43
#check BorceaVariance.inverse_root_covariance
-- BorceaVariance/SmallDegree/RootCovariance.lean:60
#check BorceaVariance.inverse_root_covariance_zero
-- BorceaVariance/SmallDegree/RootCovariance.lean:76
#check BorceaVariance.constant_of_centeredVariance_zero
-- BorceaVariance/SmallDegree/RootParameters.lean:15
#check BorceaVariance.rootVariance_identity
-- BorceaVariance/SmallDegree/RootParameters.lean:22
#check BorceaVariance.rootSecondMoment_pos
-- BorceaVariance/SmallDegree/RootParameters.lean:28
#check BorceaVariance.normalized_root_mean
-- BorceaVariance/SmallDegree/RootParameters.lean:47
#check BorceaVariance.normalized_root_secondMoment
-- BorceaVariance/SmallDegree/RootParameters.lean:64
#check BorceaVariance.normalized_root_variance
-- BorceaVariance/SmallDegree/RootParameters.lean:72
#check BorceaVariance.normalized_root_product_identity
-- BorceaVariance/SmallDegree/RootProduct.lean:13
#check BorceaVariance.normalized_root_product
-- BorceaVariance/SmallDegree/RootProduct.lean:64
#check BorceaVariance.normalized_root_product_zero
-- BorceaVariance/SmallDegree/RootProductBounds.lean:6
#check BorceaVariance.normalized_root_product_basic
-- BorceaVariance/SmallDegree/RootProductBounds.lean:26
#check BorceaVariance.normalized_root_product_variance_upper
-- BorceaVariance/SmallDegree/StableProduct.lean:10
#check BorceaVariance.radialLoss_nonneg
-- BorceaVariance/SmallDegree/StableProduct.lean:16
#check BorceaVariance.reciprocal_norm_product_radial_loss
-- BorceaVariance/SmallDegree/StableProduct.lean:48
#check BorceaVariance.normalized_stable_product
-- BorceaVariance/SmallDegree/Symmetric.lean:12
#check BorceaVariance.cofactorSum_zero
-- BorceaVariance/SmallDegree/Symmetric.lean:15
#check BorceaVariance.constantCoeff_linear_product
-- BorceaVariance/SmallDegree/Symmetric.lean:21
#check BorceaVariance.cofactorSum_cons
-- BorceaVariance/SmallDegree/Symmetric.lean:27
#check BorceaVariance.cofactorSum_eq_esymm
-- BorceaVariance/SmallDegree/Symmetric.lean:31
#check BorceaVariance.cofactorSum_tangent_lower
-- BorceaVariance/SmallDegree/Symmetric.lean:46
#check BorceaVariance.cofactorSum_smoothing
-- BorceaVariance/SmallDegree/Symmetric.lean:61
#check BorceaVariance.cofactorSum_le_normalized
-- BorceaVariance/SmallDegree/Symmetric.lean:136
#check BorceaVariance.symmetric_inequality
-- BorceaVariance/SmallDegree/SymmetricProduct.lean:7
#check BorceaVariance.cofactorSum_eq_product_inverse_sum
-- BorceaVariance/SmallDegree/SymmetricProduct.lean:20
#check BorceaVariance.symmetric_inverse_product
-- BorceaVariance/SmallDegree/SymmetricProduct.lean:44
#check BorceaVariance.normalized_norm_product_improvement
-- BorceaVariance/SmallDegree/TaoProduct.lean:6
#check BorceaVariance.real_tao_product
-- BorceaVariance/SmallDegree/TaoProduct.lean:33
#check BorceaVariance.inverse_conjugate_norm
-- BorceaVariance/SmallDegree/TaoProduct.lean:48
#check BorceaVariance.tao_product
-- BorceaVariance/ToeplitzCorollary.lean:11
#check BorceaVariance.toeplitz_corollary
-- BorceaVariance/VarianceMinimum.lean:8
#check BorceaVariance.variance_shift_identity
-- BorceaVariance/VarianceMinimum.lean:38
#check BorceaVariance.centroid_minimizes_variance
-- BorceaVariance/VarianceMinimum.lean:43
#check BorceaVariance.centroid_unique_minimizer
-- BorceaVariance/VarianceMinimum.lean:55
#check BorceaVariance.sigma2_eq_infimum
-- BorceaVariance/VarianceMoments.lean:9
#check BorceaVariance.variance_raw_moment

-- Named manuscript result index; displayed formulas are in
-- docs/theorem_inventory.tsv and docs/display-correspondence.json.

-- conj:borcea, manuscript line 111.

-- thm:main, manuscript line 135.
#check BorceaVariance.main_theorem
#check BorceaVariance.main_statement

-- cor:toeplitz-general, manuscript line 153.
#check BorceaVariance.toeplitz_corollary

-- lem:moments, manuscript line 332.
#check BorceaVariance.normalized_reciprocal_moments

-- lem:identities, manuscript line 438.
#check BorceaVariance.normalized_origin_identity_fin
#check BorceaVariance.differential_identity
#check BorceaVariance.normalized_center_identity_fin

-- lem:basic-product, manuscript line 497.
#check BorceaVariance.normalized_core_product
#check BorceaVariance.normalized_basic_product
#check BorceaVariance.phi_mono_degree
#check BorceaVariance.phi_mono_before_one
#check BorceaVariance.phi_antitone_after_one

-- lem:direct, manuscript line 870.
#check BorceaVariance.direct_bound
#check BorceaVariance.direct_retained_bound

-- lem:interpolation, manuscript line 1025.
#check BorceaVariance.centered_interpolation_first
#check BorceaVariance.centered_interpolation_second

-- lem:integral-tests, manuscript line 1248.
#check BorceaVariance.normalized_direct_integral_test
#check BorceaVariance.normalized_absolute_integral_test
#check BorceaVariance.normalized_ratio_integral_test

-- prop:large, manuscript line 1493.
#check BorceaVariance.no_normalized_counterexample_large
#check BorceaVariance.large_degree_main

-- lem:symmetric, manuscript line 2111.
#check BorceaVariance.symmetric_inequality

-- lem:inverse-root, manuscript line 2334.
#check BorceaVariance.normalized_inverse_root_mean

-- lem:root-product, manuscript line 2341.
#check BorceaVariance.normalized_root_product
#check BorceaVariance.normalized_root_product_zero

-- lem:radial-loss, manuscript line 2553.
#check BorceaVariance.reciprocal_radial_loss
#check BorceaVariance.reciprocal_product_amgm

-- lem:tao-product, manuscript line 2674.
#check BorceaVariance.tao_product

-- lem:radial-bounds, manuscript line 2685.
#check BorceaVariance.finite_radial_mean_bound
#check BorceaVariance.finite_radial_variance_bound
#check BorceaVariance.product_radial_sqrt_bound

-- lem:packing, manuscript line 2868.
#check BorceaVariance.reciprocal_packing
#check BorceaVariance.packing_power_interval_exists

-- lem:coefficients, manuscript line 3163.
#check BorceaVariance.centered_coefficients

-- lem:coefficient-test, manuscript line 3312.
#check BorceaVariance.normalized_coefficient_integral_test

-- lem:bd, manuscript line 3495.
#check BorceaVariance.bhatia_davis

-- lem:real-variance, manuscript line 3513.
#check BorceaVariance.rotated_real_variance_bound

-- lem:phase, manuscript line 3676.
#check BorceaVariance.normalized_signed_coefficient_test
#check BorceaVariance.mean_phase_integral_bound

-- lem:near, manuscript line 3933.
#check BorceaVariance.no_normalized_counterexample_near_uniform

-- lem:compact, manuscript line 4341.
#check BorceaVariance.normalized_compact

-- prop:finite, manuscript line 4508.
#check BorceaVariance.no_normalized_counterexample_finite
#check BorceaVariance.finite_degree_main
